# Generated by Django 2.0.7 on 2018-08-03 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Controle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nome')),
                ('CNPJ', models.PositiveIntegerField(verbose_name='CNPJ')),
                ('endereço', models.CharField(blank=True, max_length=30, null=True, verbose_name='Endereço')),
            ],
        ),
    ]
