# Generated by Django 2.0.7 on 2018-08-03 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controledefornecedores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controle',
            name='endereço',
        ),
    ]
