# Generated by Django 2.0.7 on 2018-08-03 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controledefornecedores', '0002_remove_controle_endereço'),
    ]

    operations = [
        migrations.AddField(
            model_name='controle',
            name='endereco',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Endereço'),
        ),
    ]
